# Generated by Django 5.0.14 on 2025-07-29 11:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('member', 'Team Member'), ('coordinator', 'Team Coordinator'), ('lead', 'Team Lead'), ('deputy_lead', 'Deputy Team Lead'), ('trainer', 'Team Trainer'), ('scheduler', 'Team Scheduler')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_assign_shifts', models.BooleanField(default=False)),
                ('can_approve_swaps', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tps_team_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('min_members_per_shift', models.PositiveIntegerField(default=1)),
                ('max_members_per_shift', models.PositiveIntegerField(default=5)),
                ('preferred_team_size', models.PositiveIntegerField(default=8)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_auto_assignment', models.BooleanField(default=True, help_text='Allow automatic shift assignments for this team')),
                ('notification_preferences', models.JSONField(default=dict, help_text='Team-specific notification settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tps_teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('is_primary_team', models.BooleanField(default=True, help_text="Whether this is the user's primary team assignment")),
                ('availability_percentage', models.PositiveIntegerField(default=100, help_text='Percentage of time available to this team', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('prefers_waakdienst', models.BooleanField(default=True)),
                ('prefers_incident', models.BooleanField(default=True)),
                ('weekend_availability', models.BooleanField(default=True)),
                ('night_shift_availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='memberships', to='teams.teamrole')),
            ],
            options={
                'verbose_name': 'Team Membership',
                'verbose_name_plural': 'Team Memberships',
                'db_table': 'tps_team_memberships',
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('weekly', 'Weekly Pattern'), ('monthly', 'Monthly Pattern'), ('quarterly', 'Quarterly Pattern'), ('custom', 'Custom Pattern')], max_length=20)),
                ('pattern_data', models.JSONField(help_text='JSON structure defining the schedule pattern')),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='teams.team')),
            ],
            options={
                'db_table': 'tps_team_schedule_templates',
                'ordering': ['team__name', 'name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
