# Generated by Django 5.0.14 on 2025-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='name',
            field=models.CharField(choices=[('member', 'Team Member'), ('coordinator', 'Team Coordinator'), ('lead', 'Team Lead'), ('deputy_lead', 'Deputy Team Lead'), ('trainer', 'Team Trainer'), ('scheduler', 'Team Scheduler'), ('operationeel', 'Operationeel'), ('tactisch', 'Tactisch')], max_length=20, unique=True),
        ),
    ]
